name: flutter-analyze

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Prepare env asset
        run: cp .env.example .env

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze
